config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  resources :recipes, only: %w(show index)

  # namespace :api do
  #   namespace :v1 do
  #     resources :texts, only: [:create]
  #   end
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  #GET recipes/random
  def index
    @tag = query.fetch(:tags, 'all')
    @refresh_params = refresh_params

    @recipes, @errors = Spoonacular::Recipe.random(query)
  end
  #GET recipes/:id/information
  def show
    @recipe = Spoonacular::Recipe.find(params[:id])
  end

  private
  def query
    #fetch(key_name, default_value): get the value if the key exists, return default_value otherwise
    params.fetch(:query, {})
  end
  def clear_cache
    params[:clear_cache].present?
  end

  def refresh_params
    refresh = { clear_cache: true }
    refresh.merge!({ query: query }) if query.present?
    refresh
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_sidebar.html.erb
<nav class="navbar Sidebar">
  <ul class="nav">
    <li class="Sidebar-item Sidebar-item--white <%= 'active' if @tag == 'all' %>">
      <%= link_to "All", root_path, class: "Sidebar-itemLink" %>
    </li>
    <li class="Sidebar-item Sidebar-item--pink <%= 'active' if @tag == 'gluten free' %>">
      <%= link_to "Gluten Free", root_path(query: { tags: 'gluten free' }), class: "Sidebar-itemLink" %>
    </li>
    <li class="Sidebar-item Sidebar-item--yellow <%= 'active' if @tag == 'dairy free' %>">
      <%= link_to "Dairy Free", root_path(query: { tags: 'dairy free' }), class: "Sidebar-itemLink" %>
    </li>
    <li class="Sidebar-item Sidebar-item--green <%= 'active' if @tag == 'vegetarian' %>">
      <%= link_to "Vegetarian", root_path(query: { tags: 'vegetarian' }), class: "Sidebar-itemLink" %>
    </li>
    <li class="Sidebar-item Sidebar-item--blue <%= 'active' if @tag == 'vegan' %>">
      <%= link_to "Vegan", root_path(query: { tags: 'vegan' }), class: "Sidebar-itemLink" %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recipe Finder</title>
  <%= csrf_meta_tags %>

<meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <link href="https://fonts.googleapis.com/css?family=Oswald:700|Droid+Serif:400,700italic" rel="stylesheet" type="text/css" />

  <%= javascript_include_tag "vendor/modernizr" %>
  <!-- <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> -->
      <!-- Following will make the react components availabe to our layout -->
    <%= javascript_pack_tag 'application' %>
</head>
<body>
  <%= render "layouts/sidebar" %>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">Recipe Finder</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">

      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>

app/views/static_pages/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1><%= @tag.capitalize %> recipes</h1>
    <%= link_to "Refresh", root_path(@refresh_params), class: "btn btn-info pull-right" %>
  </div>
</div>
<div class="row">
  <% if @errors %>
    <%= @errors[:message] %>
  <% else %>
    <% @recipes.each_slice(3) do |recipes| %>
      <div class="col-sm-3">
        <% recipes.each do |recipe| %>
          <div class="RecipeCard">
            <div class="row">
              <div class="col-xs-12">
                <%= link_to recipe_path(recipe.id) do %>
                  <%= image_tag recipe.image, class: 'img-responsive' %>
                <% end %>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-12 RecipeCard-description">
                <h4><%= recipe.title %></h4>
                <div class="Icon-container">
                  <div>
                    <% if recipe.gluten_free %>
                      <i class="Icon Icon--small Icon-glutenFree"></i>
                    <% end %>

                    <% if recipe.dairy_free %>
                      <i class="Icon Icon--small Icon-dairyFree"></i>
                    <% end %>

                    <% if recipe.vegetarian %>
                      <i class="Icon Icon--small Icon-vegetarian"></i>
                    <% end %>

                    <% if recipe.vegan %>
                      <i class="Icon Icon--small Icon-vegan"></i>
                    <% end %>
                  </div>
                  <div>
                    <i class="Icon Icon--small Icon-like"></i> <span><%= recipe.aggregate_likes %></span>
                  </div>
                  <div>
                    <i class="Icon Icon--small Icon-clock"></i> <%= recipe.ready_in_minutes %> min
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

<%= react_component 'RecipesList', { recipes: @recipes} %>


<div id="app">
  <h1>hello</h1>
</div>